FROM nginx:latest

MAINTAINER Hidekuma<d.hidekuma@gmail.com>

COPY ./dockerfiles/etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY ./dockerfiles/etc/nginx/nginx.conf /etc/nginx/nginx.conf

RUN apt-get update && apt-get install -y curl

CMD nginx
