version: '3.7'
services:
  nginx:
    container_name: nginx
    image: hidekuma-nginx:latest 
    ports:
      - 80:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s
    links:
      - uwsgi:uwsgi
    volumes:
      - ./socket:/etc/uwsgi/socket
  uwsgi:
    container_name: uwsgi
    image: hidekuma-uwsgi:latest
    command: uwsgi --ini /etc/uwsgi/webserver.ini 
    volumes:
      - ./socket:/etc/uwsgi/socket
    restart: always
